# Generated by Django 3.2.8 on 2021-11-06 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('AudioID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('SongAudio', models.FileField(null=True, upload_to='audio')),
                ('liked', models.PositiveBigIntegerField(default=0)),
                ('Album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Album.album')),
            ],
        ),
    ]
