# Generated by Django 3.2.8 on 2022-02-04 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('Audio_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Song_Audio', models.FileField(null=True, upload_to='audio')),
                ('likes', models.PositiveBigIntegerField(default=0)),
                ('Album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Album.album')),
            ],
        ),
    ]
