# Generated by Django 3.2.8 on 2022-02-04 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('Serial_No', models.AutoField(primary_key=True, serialize=False)),
                ('Album_Name', models.CharField(max_length=200)),
                ('Album_Logo', models.ImageField(default='images/No_Image.png', upload_to='images')),
                ('Release_Date', models.DateField()),
                ('Artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artist.artist')),
            ],
        ),
    ]
