# Generated by Django 3.2.8 on 2021-11-06 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('SerialNo', models.AutoField(primary_key=True, serialize=False)),
                ('AlbumName', models.CharField(max_length=200)),
                ('AlbumLogo', models.ImageField(default='No_Image.png', upload_to='')),
                ('ReleaseDate', models.DateField()),
                ('Artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artist.artist')),
            ],
        ),
    ]
