# Generated by Django 3.2.8 on 2021-11-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='AlbumLogo',
            field=models.ImageField(default='images/No_Image.png', upload_to=''),
        ),
    ]
