# Generated by Django 3.2.8 on 2021-11-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0002_alter_album_albumlogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='AlbumLogo',
            field=models.ImageField(default='No_Image.png', upload_to=''),
        ),
    ]
