# Generated by Django 3.2.8 on 2021-11-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Photo', models.ImageField(default='No_Image.png', upload_to='')),
                ('followers', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
