# Generated by Django 3.2.8 on 2021-11-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0004_alter_artist_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='Photo',
            field=models.ImageField(default='No_Image.png', upload_to=''),
        ),
    ]
