# Generated by Django 3.2.8 on 2021-11-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0006_alter_artist_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='Photo',
            field=models.ImageField(default='images/No_Image.png', upload_to='images'),
        ),
    ]
